/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApprovalTokenRouteImport } from './routes/approval.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppCreateRouteImport } from './routes/_authenticated/app.create'
import { Route as AuthenticatedAppIdeasRouteImport } from './routes/_authenticated/app.ideas'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/app.library'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated/app.templates'
import { Route as AuthenticatedAppTrendsRouteImport } from './routes/_authenticated/app.trends'
import { Route as AuthenticatedAppBrandsIndexRouteImport } from './routes/_authenticated/app.brands.index'
import { Route as AuthenticatedAppBrandsNewRouteImport } from './routes/_authenticated/app.brands.new'
import { Route as AuthenticatedAppContentNewRouteImport } from './routes/_authenticated/app.content.new'
import { Route as AuthenticatedAppCreateReelRouteImport } from './routes/_authenticated/app.create.reel'
import { Route as ApiPublicApprovalTokenRouteImport } from './routes/api/public/approval.$token'
import { Route as AuthenticatedAppBrandsBrandIdEditRouteImport } from './routes/_authenticated/app.brands.$brandId.edit'
import { Route as AuthenticatedAppContentProjectIdClientPdfRouteImport } from './routes/_authenticated/app.content.$projectId.client-pdf'
import { Route as AuthenticatedAppContentProjectIdResultRouteImport } from './routes/_authenticated/app.content.$projectId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApprovalTokenRoute = ApprovalTokenRouteImport.update({
  id: '/approval/$token',
  path: '/approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreateRoute = AuthenticatedAppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIdeasRoute = AuthenticatedAppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrendsRoute = AuthenticatedAppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBrandsIndexRoute =
  AuthenticatedAppBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBrandsNewRoute =
  AuthenticatedAppBrandsNewRouteImport.update({
    id: '/brands/new',
    path: '/brands/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentNewRoute =
  AuthenticatedAppContentNewRouteImport.update({
    id: '/content/new',
    path: '/content/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreateReelRoute =
  AuthenticatedAppCreateReelRouteImport.update({
    id: '/reel',
    path: '/reel',
    getParentRoute: () => AuthenticatedAppCreateRoute,
  } as any)
const ApiPublicApprovalTokenRoute = ApiPublicApprovalTokenRouteImport.update({
  id: '/api/public/approval/$token',
  path: '/api/public/approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppBrandsBrandIdEditRoute =
  AuthenticatedAppBrandsBrandIdEditRouteImport.update({
    id: '/brands/$brandId/edit',
    path: '/brands/$brandId/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentProjectIdClientPdfRoute =
  AuthenticatedAppContentProjectIdClientPdfRouteImport.update({
    id: '/content/$projectId/client-pdf',
    path: '/content/$projectId/client-pdf',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContentProjectIdResultRoute =
  AuthenticatedAppContentProjectIdResultRouteImport.update({
    id: '/content/$projectId/result',
    path: '/content/$projectId/result',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/approval/$token': typeof ApprovalTokenRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/create': typeof AuthenticatedAppCreateRouteWithChildren
  '/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/trends': typeof AuthenticatedAppTrendsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/app/content/new': typeof AuthenticatedAppContentNewRoute
  '/app/create/reel': typeof AuthenticatedAppCreateReelRoute
  '/api/public/approval/$token': typeof ApiPublicApprovalTokenRoute
  '/app/brands/': typeof AuthenticatedAppBrandsIndexRoute
  '/app/brands/$brandId/edit': typeof AuthenticatedAppBrandsBrandIdEditRoute
  '/app/content/$projectId/client-pdf': typeof AuthenticatedAppContentProjectIdClientPdfRoute
  '/app/content/$projectId/result': typeof AuthenticatedAppContentProjectIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/approval/$token': typeof ApprovalTokenRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/create': typeof AuthenticatedAppCreateRouteWithChildren
  '/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/trends': typeof AuthenticatedAppTrendsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/app/content/new': typeof AuthenticatedAppContentNewRoute
  '/app/create/reel': typeof AuthenticatedAppCreateReelRoute
  '/api/public/approval/$token': typeof ApiPublicApprovalTokenRoute
  '/app/brands': typeof AuthenticatedAppBrandsIndexRoute
  '/app/brands/$brandId/edit': typeof AuthenticatedAppBrandsBrandIdEditRoute
  '/app/content/$projectId/client-pdf': typeof AuthenticatedAppContentProjectIdClientPdfRoute
  '/app/content/$projectId/result': typeof AuthenticatedAppContentProjectIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/approval/$token': typeof ApprovalTokenRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/create': typeof AuthenticatedAppCreateRouteWithChildren
  '/_authenticated/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/_authenticated/app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/trends': typeof AuthenticatedAppTrendsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/brands/new': typeof AuthenticatedAppBrandsNewRoute
  '/_authenticated/app/content/new': typeof AuthenticatedAppContentNewRoute
  '/_authenticated/app/create/reel': typeof AuthenticatedAppCreateReelRoute
  '/api/public/approval/$token': typeof ApiPublicApprovalTokenRoute
  '/_authenticated/app/brands/': typeof AuthenticatedAppBrandsIndexRoute
  '/_authenticated/app/brands/$brandId/edit': typeof AuthenticatedAppBrandsBrandIdEditRoute
  '/_authenticated/app/content/$projectId/client-pdf': typeof AuthenticatedAppContentProjectIdClientPdfRoute
  '/_authenticated/app/content/$projectId/result': typeof AuthenticatedAppContentProjectIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app'
    | '/approval/$token'
    | '/app/calendar'
    | '/app/create'
    | '/app/ideas'
    | '/app/library'
    | '/app/settings'
    | '/app/templates'
    | '/app/trends'
    | '/app/'
    | '/app/brands/new'
    | '/app/content/new'
    | '/app/create/reel'
    | '/api/public/approval/$token'
    | '/app/brands/'
    | '/app/brands/$brandId/edit'
    | '/app/content/$projectId/client-pdf'
    | '/app/content/$projectId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/approval/$token'
    | '/app/calendar'
    | '/app/create'
    | '/app/ideas'
    | '/app/library'
    | '/app/settings'
    | '/app/templates'
    | '/app/trends'
    | '/app'
    | '/app/brands/new'
    | '/app/content/new'
    | '/app/create/reel'
    | '/api/public/approval/$token'
    | '/app/brands'
    | '/app/brands/$brandId/edit'
    | '/app/content/$projectId/client-pdf'
    | '/app/content/$projectId/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/approval/$token'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/create'
    | '/_authenticated/app/ideas'
    | '/_authenticated/app/library'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/trends'
    | '/_authenticated/app/'
    | '/_authenticated/app/brands/new'
    | '/_authenticated/app/content/new'
    | '/_authenticated/app/create/reel'
    | '/api/public/approval/$token'
    | '/_authenticated/app/brands/'
    | '/_authenticated/app/brands/$brandId/edit'
    | '/_authenticated/app/content/$projectId/client-pdf'
    | '/_authenticated/app/content/$projectId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApprovalTokenRoute: typeof ApprovalTokenRoute
  ApiPublicApprovalTokenRoute: typeof ApiPublicApprovalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/approval/$token': {
      id: '/approval/$token'
      path: '/approval/$token'
      fullPath: '/approval/$token'
      preLoaderRoute: typeof ApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/create': {
      id: '/_authenticated/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AuthenticatedAppCreateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ideas': {
      id: '/_authenticated/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AuthenticatedAppIdeasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/library': {
      id: '/_authenticated/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trends': {
      id: '/_authenticated/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AuthenticatedAppTrendsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brands/': {
      id: '/_authenticated/app/brands/'
      path: '/brands'
      fullPath: '/app/brands/'
      preLoaderRoute: typeof AuthenticatedAppBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brands/new': {
      id: '/_authenticated/app/brands/new'
      path: '/brands/new'
      fullPath: '/app/brands/new'
      preLoaderRoute: typeof AuthenticatedAppBrandsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/new': {
      id: '/_authenticated/app/content/new'
      path: '/content/new'
      fullPath: '/app/content/new'
      preLoaderRoute: typeof AuthenticatedAppContentNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/create/reel': {
      id: '/_authenticated/app/create/reel'
      path: '/reel'
      fullPath: '/app/create/reel'
      preLoaderRoute: typeof AuthenticatedAppCreateReelRouteImport
      parentRoute: typeof AuthenticatedAppCreateRoute
    }
    '/api/public/approval/$token': {
      id: '/api/public/approval/$token'
      path: '/api/public/approval/$token'
      fullPath: '/api/public/approval/$token'
      preLoaderRoute: typeof ApiPublicApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/brands/$brandId/edit': {
      id: '/_authenticated/app/brands/$brandId/edit'
      path: '/brands/$brandId/edit'
      fullPath: '/app/brands/$brandId/edit'
      preLoaderRoute: typeof AuthenticatedAppBrandsBrandIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/$projectId/client-pdf': {
      id: '/_authenticated/app/content/$projectId/client-pdf'
      path: '/content/$projectId/client-pdf'
      fullPath: '/app/content/$projectId/client-pdf'
      preLoaderRoute: typeof AuthenticatedAppContentProjectIdClientPdfRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content/$projectId/result': {
      id: '/_authenticated/app/content/$projectId/result'
      path: '/content/$projectId/result'
      fullPath: '/app/content/$projectId/result'
      preLoaderRoute: typeof AuthenticatedAppContentProjectIdResultRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppCreateRouteChildren {
  AuthenticatedAppCreateReelRoute: typeof AuthenticatedAppCreateReelRoute
}

const AuthenticatedAppCreateRouteChildren: AuthenticatedAppCreateRouteChildren =
  {
    AuthenticatedAppCreateReelRoute: AuthenticatedAppCreateReelRoute,
  }

const AuthenticatedAppCreateRouteWithChildren =
  AuthenticatedAppCreateRoute._addFileChildren(
    AuthenticatedAppCreateRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCreateRoute: typeof AuthenticatedAppCreateRouteWithChildren
  AuthenticatedAppIdeasRoute: typeof AuthenticatedAppIdeasRoute
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppTrendsRoute: typeof AuthenticatedAppTrendsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppBrandsNewRoute: typeof AuthenticatedAppBrandsNewRoute
  AuthenticatedAppContentNewRoute: typeof AuthenticatedAppContentNewRoute
  AuthenticatedAppBrandsIndexRoute: typeof AuthenticatedAppBrandsIndexRoute
  AuthenticatedAppBrandsBrandIdEditRoute: typeof AuthenticatedAppBrandsBrandIdEditRoute
  AuthenticatedAppContentProjectIdClientPdfRoute: typeof AuthenticatedAppContentProjectIdClientPdfRoute
  AuthenticatedAppContentProjectIdResultRoute: typeof AuthenticatedAppContentProjectIdResultRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCreateRoute: AuthenticatedAppCreateRouteWithChildren,
  AuthenticatedAppIdeasRoute: AuthenticatedAppIdeasRoute,
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppTrendsRoute: AuthenticatedAppTrendsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppBrandsNewRoute: AuthenticatedAppBrandsNewRoute,
  AuthenticatedAppContentNewRoute: AuthenticatedAppContentNewRoute,
  AuthenticatedAppBrandsIndexRoute: AuthenticatedAppBrandsIndexRoute,
  AuthenticatedAppBrandsBrandIdEditRoute:
    AuthenticatedAppBrandsBrandIdEditRoute,
  AuthenticatedAppContentProjectIdClientPdfRoute:
    AuthenticatedAppContentProjectIdClientPdfRoute,
  AuthenticatedAppContentProjectIdResultRoute:
    AuthenticatedAppContentProjectIdResultRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApprovalTokenRoute: ApprovalTokenRoute,
  ApiPublicApprovalTokenRoute: ApiPublicApprovalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
